apiVersion: v1
kind: Pod
metadata:
  name: lab-health-storage-test
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox:1.38
    command: ["sh", "-c", "sleep 300"]
    volumeMounts:
    - name: test-storage
      mountPath: /data
  volumes:
  - name: test-storage
    persistentVolumeClaim:
      claimName: lab-health-storage-test
