#!/usr/bin/env bash

###############################################################################
#
# Kubernetes Observability Lab
#
# capture-environment.sh
#
# Captures the software and Kubernetes environment used for the lab.
#
# Output:
#   docs/05-lab-environment.md
#
###############################################################################

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

if [[ ! -d "${REPO_ROOT}/.git" ]]; then
    echo "Error: Repository root not found."
    exit 1
fi

command -v docker >/dev/null 2>&1 || { echo "Error: docker not found."; exit 1; }
command -v kubectl >/dev/null 2>&1 || { echo "Error: kubectl not found."; exit 1; }
command -v kind >/dev/null 2>&1 || { echo "Error: kind not found."; exit 1; }
command -v helm >/dev/null 2>&1 || { echo "Error: helm not found."; exit 1; }

OUTPUT_FILE="${REPO_ROOT}/docs/05-lab-environment.md"

###############################################################################
# Create Markdown document
###############################################################################

cat > "${OUTPUT_FILE}" <<EOF
# Lab Environment

> **Generated File**
>
> This document is automatically generated by \`capture-environment.sh\`.
> It records the software versions and Kubernetes environment used to
> establish the baseline for this laboratory.
>
> Do not edit this file manually.

Generated on: $(date)

---

EOF

###############################################################################
# Host Environment
###############################################################################

cat >> "${OUTPUT_FILE}" <<EOF
## HOST ENVIRONMENT

| Property | Value |
|----------|-------|
| Hostname | $(hostname) |
| Operating System | $(grep PRETTY_NAME /etc/os-release | cut -d= -f2 | tr -d '"') |
| Distribution | ${WSL_DISTRO_NAME:-Native Linux} |
| Kernel | $(uname -r) |
| Architecture | $(uname -m) |

EOF

###############################################################################
# WSL Environment (if running under WSL)
###############################################################################

if [[ -n "${WSL_DISTRO_NAME:-}" ]]; then

cat >> "${OUTPUT_FILE}" <<EOF

## WSL ENVIRONMENT

\`\`\`text
$(wsl.exe --version 2>/dev/null | iconv -f UTF-16LE -t UTF-8 | tr -d '\r')
\`\`\`

EOF

fi

###############################################################################
# Docker Environment
###############################################################################

cat >> "${OUTPUT_FILE}" <<EOF

## CONTAINER RUNTIME

| Property | Value |
|----------|-------|
| Docker Client Version | $(docker version --format '{{.Client.Version}}') |
| Docker Server Version | $(docker version --format '{{.Server.Version}}') |
| Storage Driver | $(docker info --format '{{.Driver}}') |
| Cgroup Driver | $(docker info --format '{{.CgroupDriver}}') |
| Cgroup Version | $(docker info --format '{{.CgroupVersion}}') |
| Docker Root Directory | $(docker info --format '{{.DockerRootDir}}') |

---

EOF

###############################################################################
# Helm
###############################################################################

cat >> "${OUTPUT_FILE}" <<EOF

## HELM

| Property | Value |
|----------|-------|
| Helm Version | $(helm version --template='{{.Version}}' 2>/dev/null || helm version -o json 2>/dev/null | grep -o '"version":"[^"]*"' | cut -d'"' -f4) |

### Repositories

\`\`\`text
$(helm repo list 2>/dev/null)
\`\`\`

### Installed Releases

\`\`\`text
$(helm list -A 2>/dev/null)
\`\`\`

---

EOF

KUBECTL_CLIENT_VERSION="$(kubectl version --client=true 2>/dev/null | sed -n '1s/^Client Version: //p')"
KUBERNETES_SERVER_VERSION="$(kubectl version 2>/dev/null | awk '/Server Version/ {print $3}')"

###############################################################################
# Kubernetes Platform
###############################################################################

cat >> "${OUTPUT_FILE}" <<EOF

## KUBERNETES PLATFORM

### Cluster Information

\`\`\`text
$(kubectl cluster-info)
\`\`\`

### Kubernetes Version

| Property | Value |
|----------|-------|
| kubectl Client | ${KUBECTL_CLIENT_VERSION} |
| Kubernetes Server | ${KUBERNETES_SERVER_VERSION} |

### Nodes

\`\`\`text
$(kubectl get nodes -o wide)
\`\`\`

### Docker Container IP Addresses

\`\`\`text
$(docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq))
\`\`\`


EOF


cat >> "${OUTPUT_FILE}" <<EOF

### Kubernetes Pods

\`\`\`text
$(kubectl get pods -A -o wide)
\`\`\`

EOF
